patient_names = [
    "Luca Rossi",
    "Sofia Bianchi",
    "Marco Russo",
    "Elena Martini",
    "Alessio Conti",
    "Valentina Ferrari",
    "Giovanni Romano",
    "Chiara Ricci",
    "Matteo Russo",
    "Francesca Santoro",
    "Antonio Moretti",
    "Maria Ricci",
    "Davide De Luca",
    "Laura Rossi",
    "Andrea Mancini",
    "Giorgia Barbieri",
    "Paolo Rizzo",
    "Giulia Esposito",
    "Michele Ferri",
    "Martina Marino",
    "Simone Marini",
    "Sara Palumbo",
    "Francesco Gallo",
    "Elisa Greco",
    "Alessandro Fiore",
    "Anna Gentile",
    "Luca De Santis",
    "Claudia De Angelis",
    "Stefano Colombo",
    "Giuliana Ferrara",
    "Davide Russo",
    "Valeria Vitale",
    "Angelo Barbieri",
    "Sofia Leone",
    "Filippo Marchesi",
    "Maria Pellegrini",
    "Edoardo Bianco",
    "Valentina Neri",
    "Matteo Greco",
    "Aurora Rinaldi",
    "Lorenzo Bruno",
    "Camilla D'Amico",
    "Andrea Sartori",
    "Giulia Martini",
    "Davide Russo",
    "Chiara Romano",
    "Alessio Caruso",
    "Martina Farina",
    "Alessandro Bianchi",
    "Laura Pellegrino",
    "Francesco Rossetti",
    "Eleonora Rizzo",
    "Giovanni Ferri",
    "Elena De Rosa",
    "Marco Colombo",
    "Serena D'Angelo",
    "Luca Galli",
    "Alice Romano",
    "Lorenzo Mancini",
    "Beatrice Ricci",
    "Andrea Ferrara",
    "Giulia Greco",
    "Giovanni Martino",
    "Chiara Santoro",
    "Alessio De Luca",
    "Valentina Rinaldi",
    "Simone Conti",
    "Sofia Vitale",
    "Matteo Rossetti",
    "Elisa Marini",
    "Andrea Barbieri",
    "Sofia Galli",
    "Francesco De Rosa",
    "Martina Ferraro",
    "Luca Mancini",
    "Veronica Leone",
    "Alessandro Farina",
    "Elena Ferrari",
    "Alessio Romano",
    "Valentina Mancini",
    "Giovanni Ferro",
    "Chiara Marino",
    "Marco Santoro",
    "Francesca Bianco",
    "Davide Pellegrini",
    "Sofia Martino",
    "Simone Esposito",
    "Sara Rinaldi",
    "Matteo Marchesi",
    "Giulia D'Amico",
    "Andrea Barbieri",
    "Alice Marino",
    "Lorenzo Romano",
    "Elena De Luca",
    "Francesco Rizzo",
    "Valentina Romano",
    "Marco Conti",
    "Chiara Ferrara",
    "Giovanni Ferri",
    "Elisa De Santis"
]
